version: '3.1'
services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zhenya
      POSTGRES_DB: stripetest
  web:
      build: .
      restart: always
      privileged: true
      ports:
        - "8080:8080"
      command:
        bash -c "python manage.py collectstatic --noinput 
        && python manage.py makemigrations
        && python manage.py migrate
        && gunicorn top_news_scraper.wsgi -b 0.0.0.0:8080"


      environment:
         DJANGO_SETTINGS_MODULE: top_news_scraper.settings

      depends_on:
          - db

  nginx:
    build: ./nginx

    ports:
      - "8000:80"
    depends_on:
      - web
volumes:
  static_volume: